version: '3.9'


networks:
  backend:

services:
  bot:
    build: .
    container_name: telegram_bot
    env_file:
      - .env
    volumes:
      - ./app/errors.txt:/home/myuser/pdf_to_doc_bot/errors.txt
    user: myuser
    restart: always
    networks:
      - backend

